"""change users.discord_id to string

Revision ID: 11a7db6fbf0b
Revises: 570bc1fd97dc
Create Date: 2020-03-22 22:35:40.942086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a7db6fbf0b'
down_revision = '570bc1fd97dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id', existing_type=sa.Integer(), type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id', existing_type=sa.String(), type_=sa.Integer())
    # ### end Alembic commands ###
