"""initial

Revision ID: 570bc1fd97dc
Revises: 
Create Date: 2020-03-22 18:53:11.177023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570bc1fd97dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesho_tapni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.Column('voice_channel_greeting', sa.String(), nullable=True),
    sa.Column('is_bot_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('vqrno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('play_music', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_permissions')
    op.drop_table('vqrno')
    op.drop_table('users')
    op.drop_table('pesho_tapni')
    # ### end Alembic commands ###
