"""added bot permissions for commands

Revision ID: ff366dee535e
Revises: 11a7db6fbf0b
Create Date: 2020-03-25 01:32:03.670959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff366dee535e'
down_revision = '11a7db6fbf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('add_to_commands', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('play_music', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'play_music')
    op.drop_column('users', 'add_to_commands')
    # ### end Alembic commands ###
